package com.developmentavk.avk_app_kotlin.app.utils.const

object ConstFields {
    const val COL_NAME = "name"
    const val COL_MODEL = "model"
    const val COL_STATUS_DATE = "status_date"
    const val COL_BRAND = "brand"
    const val COL_MEMORY = "memory"
    const val COL_COLOR = "color"
    const val COL_SPEC = "spec"
    const val COL_MODEL_CODE = "model_code"
    const val COL_PCS = "pcs"
    const val COL_PCS_FACT = "pcs_fact"
    const val COL_IS_CHECK = "is_check"
    const val COL_PHONE = "phone"
    const val COL_CATEGORY = "category"
    const val COL_HKZONE = "hkzone"
    const val COL_BARCODE = "barcode"
    const val COL_ADDRESS = "address"
    const val COL_ADDRESS2 = "address2"
    const val COL_SUPPLIER = "supplier"
    const val COL_INSTRUCTION = "instruction"
    const val COL_PICKUP_DATE = "pickup_date"
    const val COL_BREAK_START = "break_start"
    const val COL_BREAK_END = "break_end"
    const val COL_MANAGER = "manager"
    const val COL_PICKUPER = "pickuper"
    const val COL_MASTERBOX = "masterbox"
    const val COL_ASK_IS_UNSEAL = "ask_isunseal"
    const val COL_UID = "uid"
    const val COL_UNSEAL = "unseal"
    const val COL_PHOTO = "photo"
    const val COL_CODE_SUPPLIER = "code_supplier"
    const val COL_PURCHASE_DATE = "purchase_date"
    const val COL_REMAIN_PCS = "remain_pcs"
    const val COL_IS_UNSEAL = "is_unseal"
    const val COL_IS_UNSEAL_TXT = "is_unseal_txt"
    const val COL_UNSEAL_UID = "unseal_uid"
    const val COL_CATEGORY_CLOCK = "category_clock"
    const val COL_WAREHOUSE = "warehouse"
    const val COL_DESCRIPTION = "description"
    const val COL_NEED_IMEI = "need_imei"
    const val COL_ENABLE = "enable"
    const val COL_ALGORITHM = "algorithm"
    const val COL_MEMCOLSPEC = "memcolspec"
}

object TableNames{
    const val TableBarCodes = "table_barcode"
    const val TableGoods = "table_goods"
    const val TableSuppliers = "table_suppliers"
}